---
openapi: 3.0.0
info:
  title: Image Processing API
  description: API for performing various image processing operations
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/VANDANAGANDEPALLI043/ImageProcessingAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8000
  description: Local development server
paths:
  /process_image:
    post:
      summary: Process Image
      description: Processes the provided image with specified operations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageProcessingRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageProcessingResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
components:
  schemas:
    ImageProcessingRequest:
      required:
      - image_data
      - operations
      type: object
      properties:
        image_data:
          type: string
          format: binary
        operations:
          type: array
          items:
            $ref: '#/components/schemas/ImageOperation'
    ImageProcessingResponse:
      type: object
      properties:
        processed_image_data:
          type: string
          format: binary
        thumbnail_image_data:
          type: string
          format: binary
        error_message:
          type: string
    ImageOperation:
      type: object
      properties:
        name:
          type: string
        degrees:
          type: integer
        axis:
          type: string
        percentage:
          type: integer
        thumb:
          type: array
          items:
            type: integer
        scale:
          type: string
        side:
          type: string
